### PR TITLE
upgraded index file to support bootstrap included navbar

### PR DESCRIPTION
**Pull request by plod**
what do we think @freeCodeCampBridgend/website-contributers

### CODE REVIEW

**Review by MrPrew — CHANGES_REQUESTED** [review]
Looks neat and clean but the FCC Bridgend logo within index.html isn't referenced in the freeCodeCamp.css file so isn't resizing correctly. I've attached a possible fix.

[fccLogoFix.zip](https://github.com/freeCodeCampBridgend/website/files/3044042/fccLogoFix.zip)

**Comment by plod** [comment]
> Looks neat and clean but the FCC Bridgend logo within index.html isn't referenced in the freeCodeCamp.css file so isn't resizing correctly. I've attached a possible fix.
> 
> [fccLogoFix.zip](https://github.com/freeCodeCampBridgend/website/files/3044042/fccLogoFix.zip)

commit the fix to the branch ;)

**Comment by MrPrew** [comment]
> 
> 
> > Looks neat and clean but the FCC Bridgend logo within index.html isn't referenced in the freeCodeCamp.css file so isn't resizing correctly. I've attached a possible fix.
> > [fccLogoFix.zip](https://github.com/freeCodeCampBridgend/website/files/3044042/fccLogoFix.zip)
> 
> commit the fix to the branch ;)

Done.. I think!? Github n00b! :-D

**Comment by plod** [comment]
LGTM but I'd like sign off off @ddddamian

**Review by ddddamian — APPROVED** [review]
Looks good. Good works guys

**Pull request merged**
